start = xml
xml = element xml { source, poem }

source = element source { title?, author?, date? }
title = element title { level, text }
level = attribute level { text }
author = element author { text }
date = element date { when }
when = attribute when { xsd:gYear }

poem = element poem { element title { attribute level { text }, text }?, lg+ }
lg = element lg { ln+ }
ln = element ln {n, mixed { placeName*, place*, motif* } }
n = attribute n { xsd:int }
placeName = element placeName { attribute ref { text }, text }
place = element place { attribute ref { text }, text }
motif = element motif { text }


