start = xml
xml = element xml { source, poem }

#metadata
source = element source { title?, author?, date? }
author = element author { text }
date = element date { when }
when = attribute when { xsd:gYear }

#used for both source and poem
title = element title { level, text }
level = attribute level { text }

#text content
poem = element poem { title?, lg+ }
lg = element lg { ln+ }
ln = element ln {n, mixed { (placeName | place | motif)* } }
n = attribute n { xsd:int }
ref = attribute ref { text } #used for both placeName and place
placeName = element placeName { ref, text }
place = element place { ref, text }
motif = element motif { text }


